services:
  - type: web
    name: homecalendar-backend
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
